import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import SignUp from './components/SignUp'
import LoginPage from './components/LoginPage'
import RegistrationLayout from './components/RegistrationLayout'




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {/* {children} */}
        {/* <LoginPage /> */}
      <RegistrationLayout />
        {/* <SignUp /> */}
        </body>
    </html>
  )
}
